#pragma once

enum class BeltEvent {
    SENSORS_INITIALIZED,
    SENSOR_FAILURE,
    BUTTON_PRESSED,
    BUTTON_DOUBLE_PRESSED,
    GOOD_BRACE_DETECTED,
    POOR_BRACE_DETECTED,
    CALIBRATION_COMPLETE,
    CALIBRATION_TIMEOUT,
    FEEDBACK_COMPLETE,
    NO_EVENT = -1
};