#pragma once

enum class BeltEvent {
    SENSORS_INITIALIZED,
    SENSOR_FAILURE,
    DEVICE_PAIRED,
    PAIRING_TIMEOUT,
    START_CALIBRATION,
    BASELINE_COMPLETE,
    CALIBRATION_COMPLETE,
    CALIBRATION_CANCELLED,
    LIFT_STARTED,
    GOOD_BRACE_DETECTED,
    POOR_BRACE_DETECTED,
    LIFT_COMPLETE,
    FEEDBACK_COMPLETE,
    INACTIVITY_TIMEOUT,
    ERROR_RESOLVED,
    ERROR_TIMEOUT
};